# Generated by Django 2.2.6 on 2019-10-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191005_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Нет данных', max_length=255, verbose_name='Поле - Ваше имя')),
                ('company', models.CharField(blank=True, default='Нет данных', max_length=255, verbose_name='Поле - Телефон')),
                ('phone', models.CharField(default='Нет данных', max_length=255, verbose_name='Поле - Телефон')),
                ('email', models.EmailField(blank=True, default='Нет данных', max_length=255, verbose_name='Поле - Email')),
                ('message', models.TextField(blank=True, default='Нет данных', max_length=255, verbose_name='Поле - Сообщение')),
            ],
        ),
    ]
