# Generated by Django 2.2.6 on 2019-10-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='detailImage',
            field=models.ImageField(blank=True, upload_to='portfolio_img/', verbose_name='Изображение для баннера'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='shortDescription',
            field=models.CharField(default='', max_length=200, verbose_name='Короткое описание'),
        ),
    ]
