# Generated by Django 2.2.6 on 2019-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191012_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='linkText',
            field=models.CharField(default='', max_length=100, verbose_name='Надпись на ссылке'),
        ),
    ]
